
on:
  push:
    branches:
    - main


jobs:
  deploy:
    name: deploy to prod
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/www/cleaning
            git pull
            npm run build
            pm2 reload 0
